# rate at which data should be published
frequency: 1 # Hz

# Sensor heating params
gas_heater : 
  - temperature: 320
  - gas_heater_duration: 150
  - profile: 0

# air quality params
air_quality: 
  - enable: False
  - burn_time: 300 # s
  - hum_baseline: 40
  - hum_weight: 0.25
k: {"enable": 1, "fsfqf": 3}
          




