# hardware interface params
i2c_bus: 5

# rate at which data should be published
frequency: 1 # Hz

# Sensor heating params
gas_heater : 
  - temperature: 320
  - duration: 150
  - profile: 0

# air quality params
air_quality: 
  - enable: False
  - burn_time: 300 # s
  - hum_baseline:  # humidity baseline value
  - hum_weight: 0.25 # humidity weifht, impact of humidity on quality

          




